### ISSUE TITLE
[BUG] - KeyError: 'hasMore'

### ISSUE THREAD

**Issue by rnyPlanet** [davidteather/TikTok-Api#363] opened 2020-11-16 16:15 UTC
trying to download a video using code

https://github.com/davidteather/TikTok-Api/issues/311#issuecomment-721164493

just want to download video (get bytes)

```
File "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\TikTokApi\tiktok.py", line 406, in userPosts
    if not res["hasMore"] and not first:
KeyError: 'hasMore'
```

 - OS: Windows 10
 - TikTokApi Version 3.7.9

**Comment by rnyPlanet** [comment] 2020-11-16 16:41
https://github.com/nemanjastokuca/tiktok-downloader/blob/main/tiktok-downloader.py#L27 maybe should add the same line? I don't really know this library

**Comment by zkquin** [comment] 2020-11-16 17:15
This also occurs with byUsername randomly.

**Comment by vdemay** [comment] 2020-11-16 17:19
Try to use a `custom_verifyFp=`
This error appears when response from Tiktok is blocked: json returned by tiktok is not the expected response but a kind of json error message.

**Comment by rnyPlanet** [comment] 2020-11-16 17:32
> Try to use a `custom_verifyFp`
> This error appears when response from Tiktok is blocked: json returned by tiktok is not the expected response but a kind of json error message.

do I understand correctly that custom_verifyFp is from my tick tok cookie?

**Comment by ddupreez2** [comment] 2020-11-17 01:14
I am also having this issue. Is there a fix for this?

**Comment by septfish** [comment] 2020-11-17 03:06
> Try to use a `custom_verifyFp`
> This error appears when response from Tiktok is blocked: json returned by tiktok is not the expected response but a kind of json error message.

Is custom_verifyFp constant? What is the decision? Where should I get it? How can I change it?

**Comment by rnyPlanet** [comment] 2020-11-17 07:09
> Is custom_verifyFp constant? What is the decision? Where should I get it? How can I change it?

https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/tiktok.py#L158 i changed here. 
but I guess you can try 
```
api = TikTokApi(custom_verifyFP = "CODE")
```
```s_v_web_id ``` you can take it from the tiktok website in cookies

**Comment by hoai97nam** [comment] 2020-11-17 07:47
> https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/tiktok.py#L158 i changed here.
> but I guess you can try
> 
> ```
> api = TikTokApi(custom_verifyFP = "CODE")
> ```
> 
> `s_v_web_id ` you can take it from the tiktok website in cookies

did it work on you ?

**Comment by rnyPlanet** [comment] 2020-11-17 07:53
> did it work on you ?

it seems to have gotten better. I also added some data to the cookies taken from the site
![Screenshot_2](https://user-images.githubusercontent.com/33624178/99361259-7d879e00-28ba-11eb-9913-c5a51d631c58.png)

**Comment by cesarblancg** [comment] 2020-11-17 18:57
I tried this code on my computer and on my vps(which has a bot that handles approx 4k downloads every day) and it works well.

Idk if TikTok bans IP, but seems a nice workaround.

```
import random
import requests
import random

headers_list = [
    # Firefox 77 Mac
     {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Referer": "https://www.google.com/",
        "DNT": "1",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1"
    },
    # Firefox 77 Windows
    {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate, br",
        "Referer": "https://www.google.com/",
        "DNT": "1",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1"
    },
    # Chrome 83 Mac
    {
        "Connection": "keep-alive",
        "DNT": "1",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Dest": "document",
        "Referer": "https://www.google.com/",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8"
    },
    # Chrome 83 Windows 
    {
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Sec-Fetch-Site": "same-origin",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-User": "?1",
        "Sec-Fetch-Dest": "document",
        "Referer": "https://www.google.com/",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9"
    }
]

def get_verifyFP(headers):
    session = requests.Session()
    session.headers = headers
    session.get('https://www.tiktok.com/', allow_redirects=True)
    return session.cookies.get_dict()['tt_csrf_token']

for i in range(0,100):
    headers = random.choice(headers_list)
    print(get_verifyFP(headers))
```

**Comment by ddupreez2** [comment] 2020-11-18 16:27
Hey the above is still not working for me.

**Comment by ddupreez2** [comment] 2020-11-18 16:37
> api = TikTokApi(custom_verifyFP = "CODE")

Change this to: 
api.trending(custom_verifyFp="verify_...")

**Comment by zkquin** [comment] 2020-11-18 21:01
Had to feed through the user-agent and cookies to get anywhere.

**Comment by rnyPlanet** [comment] 2020-11-19 07:21
> Had to feed through the user-agent and cookies to get anywhere.

what do you mean?

**Comment by zkquin** [comment] 2020-11-19 12:16
getUser started to cause me issue too.

So far I can get getUser to work, whereas before it would only work 10% of the time. However, byUsername is still giving me problems - only returning "Invalid Response". 

I used the user-agent and the entire cookie from the browser used to sign-in with.

**Comment by zkquin** [comment] 2020-11-19 12:30
I take that all back. Now getUser is seemingly working fine.

Now I'm getting a `requests.exceptions.SSLError: HTTPSConnectionPool(host='tiktok.com', port=443): Max retries exceeded with url:  /@imgalina?lang=en (Caused by SSLError(SSLCertVerificationError("hostname 'tiktok.com' doesn't match either of '*.snssdk.com', 'snssdk.com'")))`

**Comment by davidteather** [comment] 2020-11-21 17:18
Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

**Comment by rnyPlanet** [comment] 2020-11-22 12:10
> Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

https://github.com/mrzlab630/TikTok-Anti-puzzle-captcha can try to solve the captcha using this library? I am trying to solve the captcha using opencv, but so far it does not work

**Comment by rnyPlanet** [comment] 2020-11-29 08:49
> Update the API to the latest version. There's better error handling now which should give you a better idea of how to proceed. Most likely it's a custom_verifyFp issue

i solved the problem. removed the random generation and set cookies from the site (tt_webid, tt_webid_v2, tt_csrf_token, s_v_web_id)
![image](https://user-images.githubusercontent.com/33624178/100537353-8704f480-3230-11eb-8d43-5cb280351ef3.png)

**Comment by davidteather** [comment] 2020-12-03 02:19
just use #347 now

**Closed by davidteather** 2020-12-03 02:19 UTC
Labels: bug

**Comment by davidteather** [comment] 2021-03-30 17:45
I recommend following the youtube video linked in the readme

**Comment by MagMueller** [comment] 2021-03-31 05:37
> I recommend following the youtube video linked in the readme

Thank you it was really helpful, but i still get the same error, even after i deleted my s_v_web_id, reloaded the page and tried with the new s_v_web_id. 
I am not logged in in Tiktok and trying just to get 1 video.

Did they blocked some other id from me?

**Comment by Syahrol13** [comment] 2021-09-13 10:46
Hi, I also has the same issue as @MagMueller, is there any way to solve this?
