### ISSUE TITLE
[BUG] - KeyError

### ISSUE THREAD

**Issue by Tracer-Shield** [davidteather/TikTok-Api#956] opened 2022-10-10 12:16 UTC
Code:

```python
from TikTokApi import TikTokApi
api = TikTokApi()
for video in api.trending.videos():
    print(video.as_dict)
```

Error:

```python
Traceback (most recent call last):
  File "d:\TikTok\TikTok ID Samples.py", line 3, in <module>
    for video in api.trending.videos():
  File "C:\Users\fun64\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\api\trending.py", line 40, in videos
    ttwid = spawn.cookies["ttwid"]
  File "C:\Users\fun64\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\fun64\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='ttwid', domain=None, path=None"
```

**Comment by bamboo-wood** [comment] 2022-10-11 06:48
i'm same

**Comment by nikky78** [comment] 2022-10-13 14:46
same

**Comment by anatoleblanc** [comment] 2022-10-13 17:48
+1

**Comment by gustavsogard** [comment] 2022-10-14 10:53
I have the same issue

**Comment by janith-jware** [comment] 2022-10-15 16:51
Same here

**Comment by kamihork** [comment] 2022-10-16 13:04
I'm having the same error and haven't resolved it either.
Incidentally, there is already a similar issue.
https://github.com/davidteather/TikTok-Api/issues/890
https://github.com/davidteather/TikTok-Api/issues/849

**Comment by kamihork** [comment] 2022-10-16 13:46
I think I can solve this problem by logging into tiktok and importing the cookie
https://github.com/davidteather/TikTok-Api/issues/891#issuecomment-1148930488

**Comment by Spiderfield** [comment] 2022-10-17 07:29
Same error here. V5.2.2

**Comment by nickmurr** [comment] 2022-10-20 11:32
Same error too V5.2.2

**Comment by cozybear** [comment] 2022-10-20 16:04
Same error here, tried importing the cookies manually but no luck

**Comment by nixman2** [comment] 2022-10-20 23:27
Same error here. Please fix

**Comment by developerfromjokela** [comment] 2022-10-23 11:11
TikTok blocks user agent python-requests, that's the cause.

**Comment by rushabh7874** [comment] 2022-10-25 11:22
Same error here. V5.2.2. Please fix it

**Comment by DiMiTriFrog** [comment] 2022-10-31 19:25
Same

**Comment by Sx3** [comment] 2022-11-05 20:32
> I think I can solve this problem by logging into tiktok and importing the cookie [#891 (comment)](https://github.com/davidteather/TikTok-Api/issues/891#issuecomment-1148930488)

this works one time and then not working ...

**Comment by Joystickplays** [comment] 2022-11-06 10:46
Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.

You change...
```py
spawn = requests.head(
    "https://www.tiktok.com",
    proxies=Search.parent._format_proxy(processed.proxy),
    **Search.parent._requests_extra_kwargs
)
ttwid = spawn.cookies["ttwid"]
```
to...
```py
spawn = requests.get(
    "https://www.tiktok.com",
    proxies=Search.parent._format_proxy(processed.proxy),
    **Search.parent._requests_extra_kwargs,
    headers={
        'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
    }
)
ttwid = spawn.cookies.get_dict()["ttwid"]
```
Basically, I changed the request type from HEAD to GET, and added a User-Agent.
I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.

**Comment by gaiaml** [comment] 2022-11-06 12:20
> Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.
> 
> You change...
> 
> ```python
> spawn = requests.head(
>     "https://www.tiktok.com",
>     proxies=Search.parent._format_proxy(processed.proxy),
>     **Search.parent._requests_extra_kwargs
> )
> ttwid = spawn.cookies["ttwid"]
> ```
> 
> to...
> 
> ```python
> spawn = requests.get(
>     "https://www.tiktok.com",
>     proxies=Search.parent._format_proxy(processed.proxy),
>     **Search.parent._requests_extra_kwargs,
>     headers={
>         'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
>     }
> )
> ttwid = spawn.cookies.get_dict()["ttwid"]
> ```
> 
> Basically, I changed the request type from HEAD to GET, and added a User-Agent. I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.
> 
> Quick notice: Some other python files still have that old code. So just replace that old code with the new one. If it still errors, try to get some common sense and maybe you can fix it.

Hi,
I confirm that the exception is gone.

I tried on it trending.py but then :

api.trending.videos()) -> returns something void. Any ideas?

**Comment by Joystickplays** [comment] 2022-11-06 13:19
> > Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.
> > You change...
> > ```python
> > spawn = requests.head(
> >     "https://www.tiktok.com",
> >     proxies=Search.parent._format_proxy(processed.proxy),
> >     **Search.parent._requests_extra_kwargs
> > )
> > ttwid = spawn.cookies["ttwid"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to...
> > ```python
> > spawn = requests.get(
> >     "https://www.tiktok.com",
> >     proxies=Search.parent._format_proxy(processed.proxy),
> >     **Search.parent._requests_extra_kwargs,
> >     headers={
> >         'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
> >     }
> > )
> > ttwid = spawn.cookies.get_dict()["ttwid"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically, I changed the request type from HEAD to GET, and added a User-Agent. I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.
> > Quick notice: Some other python files still have that old code. So just replace that old code with the new one. If it still errors, try to get some common sense and maybe you can fix it.
> 
> Hi, I confirm that the exception is gone.
> 
> I tried it on trending.py but then :
> 
> api.trending.videos() -> returns something void. Any ideas?

Can you tell me what "something void" mean? Sorry. Is it returning something empty?

**Comment by gaiaml** [comment] 2022-11-06 13:54
> > > Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.
> > > You change...
> > > ```python
> > > spawn = requests.head(
> > >     "https://www.tiktok.com",
> > >     proxies=Search.parent._format_proxy(processed.proxy),
> > >     **Search.parent._requests_extra_kwargs
> > > )
> > > ttwid = spawn.cookies["ttwid"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to...
> > > ```python
> > > spawn = requests.get(
> > >     "https://www.tiktok.com",
> > >     proxies=Search.parent._format_proxy(processed.proxy),
> > >     **Search.parent._requests_extra_kwargs,
> > >     headers={
> > >         'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
> > >     }
> > > )
> > > ttwid = spawn.cookies.get_dict()["ttwid"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Basically, I changed the request type from HEAD to GET, and added a User-Agent. I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.
> > > Quick notice: Some other python files still have that old code. So just replace that old code with the new one. If it still errors, try to get some common sense and maybe you can fix it.
> > 
> > 
> > Hi, I confirm that the exception is gone.
> > I tried it on trending.py but then :
> > api.trending.videos() -> returns something void. Any ideas?
> 
> Can you tell me what "something void" mean? Sorry. Is it returning something empty?

Correct, something empty -> []
Probably tiktok changed something to get the trends? (a route or different parameter names)

**Comment by SteveMelons** [comment] 2022-11-09 17:39
> Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.
> 
> You change...
> 
> ```python
> spawn = requests.head(
>     "https://www.tiktok.com",
>     proxies=Search.parent._format_proxy(processed.proxy),
>     **Search.parent._requests_extra_kwargs
> )
> ttwid = spawn.cookies["ttwid"]
> ```
> 
> to...
> 
> ```python
> spawn = requests.get(
>     "https://www.tiktok.com",
>     proxies=Search.parent._format_proxy(processed.proxy),
>     **Search.parent._requests_extra_kwargs,
>     headers={
>         'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
>     }
> )
> ttwid = spawn.cookies.get_dict()["ttwid"]
> ```
> 
> Basically, I changed the request type from HEAD to GET, and added a User-Agent. I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.
> 
> Quick notice: Some other python files still have that old code. So just replace that old code with the new one. If it still errors, try to get some common sense and maybe you can fix it.

You should make a PR

**Comment by K0rpse** [comment] 2022-11-12 19:48
I found a solution but I don't know why it works.

Replace this
`ttwid = spawn.cookies["ttwid"]`
by this
`ttwid = ""`

**Comment by souffyan** [comment] 2022-12-03 11:41
> > Hey everyone! I managed to get a fix (hopefully it works to others). I changed `C:\Users\user\AppData\Local\Programs\Python\Python310\Lib\site-packages\TikTokApi\api\search.py` for this.
> > You change...
> > ```python
> > spawn = requests.head(
> >     "https://www.tiktok.com",
> >     proxies=Search.parent._format_proxy(processed.proxy),
> >     **Search.parent._requests_extra_kwargs
> > )
> > ttwid = spawn.cookies["ttwid"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to...
> > ```python
> > spawn = requests.get(
> >     "https://www.tiktok.com",
> >     proxies=Search.parent._format_proxy(processed.proxy),
> >     **Search.parent._requests_extra_kwargs,
> >     headers={
> >         'User-Agent': "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.52 Safari/536.5"
> >     }
> > )
> > ttwid = spawn.cookies.get_dict()["ttwid"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically, I changed the request type from HEAD to GET, and added a User-Agent. I compiled all the answers I found from trying to fix this error, so technically this piece of work was a team effort.
> > Quick notice: Some other python files still have that old code. So just replace that old code with the new one. If it still errors, try to get some common sense and maybe you can fix it.
> 
> Hi, I confirm that the exception is gone.
> 
> I tried it on trending.py but then :
> 
> api.trending.videos() -> returns something void. Any ideas?

hi  @Joystickplays . J'ai le même problème avez vous trouvé une solution ?

**Comment by hamouddd** [comment] 2022-12-18 00:10
@souffyan did u find a solution? it still dont work :/

**Comment by davidteather** [comment] 2023-08-08 22:02
Should be fixed in V6 I think?

**Closed by davidteather** 2023-08-08 22:02 UTC
Labels: bug
