### ISSUE TITLE
[BUG] - 'TikTokApi' object has no attribute 'width'

### ISSUE THREAD

**Issue by QI-Tony** [davidteather/TikTok-Api#400] opened 2020-11-30 19:57 UTC
‘’‘
from TikTokApi import TikTokApi

api = TikTokApi.get_instance()

print(api.search_for_users('james', count=10))
’‘’
I post this question cuz I would like to know how to use the 'search_for_users' method.  What should I input on '**kwargs'?
If I did not input anything on kwargs, it will report that 'TikTokApi' object has no attribute 'width'.
Could you give me some feedback?
Thanks!

**Comment by demon071** [comment] 2020-12-01 14:33
https://t.tiktok.com/api/item_list/?count=30&id=78514100276&type=1&secUid=&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=FR&priority_region=FR&language=VN&verifyFp=verify_khr3jabg_V7ucdslq_Vrw9_4KPb_AJ1b_Ks706M8zIJTq
You can use request for api [here](https://github.com/demon071/Tiktok-API-Python)

**Comment by davidteather** [comment] 2020-12-03 03:10
@demon071 what on earth kind of black magic is that request

**Comment by QI-Tony** [comment] 2020-12-03 19:34
> @demon071 what on earth kind of black magic is that request

So, how to use search_for_users methods?

**Comment by Lerbytech** [comment] 2020-12-04 14:36
I checked demon071's API realisation and have to admit that it is quite useful. Still - is there any progress in understanding reasons of this issue ?

**Comment by davidteather** [comment] 2020-12-04 17:42
@QI-Tony If TikTokApi has to attribute width it probably means your browser isn't launching for whatever reason you can try `api = TikTokApi(use_selenium=True)`

**Comment by davidteather** [comment] 2020-12-04 17:44
Yeah @demon071 found what I think is TikTok's test server endpoints I've implemented it on the nightly branch and #409 but want to see if it holds before switching it as it IS a friday so they might deploy today

**Comment by Lerbytech** [comment] 2020-12-15 21:39
so,  @davidteather  - did it stand after friday? I see that url is working, though have no idea of other endpoints

**Comment by SpyderRivera** [comment] 2020-12-16 21:29
This helped me
> @QI-Tony If TikTokApi has to attribute width it probably means your browser isn't launching for whatever reason you can try `api = TikTokApi(use_selenium=True)`

I then had to download chromedriver and add to `/usr/local/bin`

I am on a Mac

**Comment by davidteather** [comment] 2020-12-20 01:57
> so, @davidteather - did it stand after friday? I see that url is working, though have no idea of other endpoints

Yes you can do `api = TikTokApi.get_instance(use_test_endpoints=True)`

Gonna close the issue because selenium support has been added.

**Closed by davidteather** 2020-12-20 01:57 UTC
Labels: bug

**Comment by sbarbs95** [comment] 2021-05-04 15:15
Hi, I'm getting this error even after adding 
`api = TikTokApi.get_instance(use_test_endpoints=True)`

Do you have any tip? Is it possibile to set the field  (width) with a custom value?
Thanks

**Comment by davidteather** [comment] 2021-05-05 01:14
This means playwright cannot launch doesn't work on centos and must be python3.7+ if that doesn't work [try their sample scripts and file issues with them](https://github.com/microsoft/playwright-python)

**Comment by sbarbs95** [comment] 2021-05-05 08:08
Thank you @davidteather , I'll check what is working for playwright!

**Comment by sbarbs95** [comment] 2021-05-06 08:17
Hi @davidteather , I come back to you to let you know I'm stuck with this issue trying to deploy an AWS lambda with Docker.
It fails with:
```
 [ERROR] Error: 
================================================================================
"webkit" browser was not found.
Please complete Playwright installation via running
"python -m playwright install"
================================================================================
```

And I have `playwright==1.10.0` in the requirements.txt + Dockerfile looks like this:
```
FROM amazon/aws-lambda-python:3.7

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python -m playwright install

COPY second_lambda.py .

CMD ["second_lambda.lambda_handler"]
```

Do you, or anyone, have any suggestion to make it work? I know AWS has some trouble running playwright, but maybe I'm missing a simple config. Thanks in advance!

**Comment by Mikami382** [comment] 2021-05-23 23:43
Hi, I came around this issue and found a fix. The cause of this is probably you're running Linux without a display or virtual display. The solution is to insert the following options in the chrome driver (browser_selenium.py):

```
        options = webdriver.ChromeOptions()
        options.add_argument('--no-sandbox')
        options.add_argument('--window-size=1420,1080')
        options.add_argument('--headless')
        options.add_argument('--disable-gpu')
        options.add_argument("log-level=2")
```

@davidteather tagging you just in case you want to update it

**Comment by josh-ashkinaze** [comment] 2021-09-17 13:15
@Mikami382 Where is this `browser_selenium.py` located? I checked selenium in my site packages and I don't have any such file. Or are you passing in these arguments in your script? And if so, can you show how you the pass in the modified chromedriver to to TikTokApi?
