### ISSUE TITLE
[BUG] - api.trending.videos() returns an empty generator

### ISSUE THREAD

**Issue by GagGev** [davidteather/TikTok-Api#995] opened 2023-02-04 16:22 UTC
api.trending.videos() generator doesn't generate any Video object

```py
from TikTokApi import TikTokApi

api = TikTokApi()
for video in api.trending.videos():
    print("OK")
```

The code above never prints OK, which means, that no Video object is generated.

 - OS: Windows 10
 - TikTokApi Version - v5

**Comment by Natgho** [comment] 2023-02-06 20:02
Is anyone reading here?

**Comment by yuqingcuiyuki** [comment] 2023-02-06 21:35
same for me

**Comment by hbicnoujaim** [comment] 2023-02-09 05:46
Having the same issue!

**Comment by shichordev** [comment] 2023-02-13 10:49
Same here. The response returned from TikTok is: {'status_code': 0}

**Comment by mmattyg** [comment] 2023-02-13 13:36
same (MacOS)

**Comment by c64er4ever** [comment] 2023-02-15 16:22
Hi all,
I found out that the issue is caused because TikTok now expects to receive msToken in the cookie. To fix the issue, I added msToken in _get_cookies, as follows:
`        if kwargs.get("force_verify_fp_on_cookie_header", False):
            return {
                "tt_webid": device_id,
                "tt_webid_v2": device_id,
                "csrf_session_id": kwargs.get("csrf_session_id"),
                "tt_csrf_token": "".join(
                    random.choice(string.ascii_uppercase + string.ascii_lowercase)
                    for i in range(16)
                ),
                "s_v_web_id": verifyFp,
                "msToken": "<generated msToken>",
                "ttwid": kwargs.get("ttwid"),
            }
        else:
            return {
                "tt_webid": device_id,
                "tt_webid_v2": device_id,
                "csrf_session_id": kwargs.get("csrf_session_id"),
                "tt_csrf_token": "".join(
                    random.choice(string.ascii_uppercase + string.ascii_lowercase)
                    for i in range(16)
                ),
                "msToken": "<generated msToken>",
                "ttwid": kwargs.get("ttwid"),`

I used msToken that was generated by the browser in the request. If anyone has an idea how to automatically generate a valid msToken, please advise :)

**Comment by rtheodoro** [comment] 2023-02-23 21:44
> Hi all, I found out that the issue is caused because TikTok now expects to receive msToken in the cookie. To fix the issue, I added msToken in _get_cookies, as follows: ` if kwargs.get("force_verify_fp_on_cookie_header", False): return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "s_v_web_id": verifyFp, "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"), } else: return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"),`
> 
> I used msToken that was generated by the browser in the request. If anyone has an idea how to automatically generate a valid msToken, please advise :)

Can you please tell me more about it? I have been trying a lot, but failing.

**Comment by qcheng-dev** [comment] 2023-02-25 21:53
Same issue with me.

**Comment by SyrupTheSrc** [comment] 2023-02-28 00:27
> > Hi all, I found out that the issue is caused because TikTok now expects to receive msToken in the cookie. To fix the issue, I added msToken in _get_cookies, as follows: ` if kwargs.get("force_verify_fp_on_cookie_header", False): return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "s_v_web_id": verifyFp, "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"), } else: return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"),`
> > I used msToken that was generated by the browser in the request. If anyone has an idea how to automatically generate a valid msToken, please advise :)
> 
> Can you please tell me more about it? I have been trying a lot, but failing.

Same here @qcheng-dev & @rtheodoro .  Any information on how to get this API to work?

**Comment by rtheodoro** [comment] 2023-02-28 20:00
> Same here @qcheng-dev & @rtheodoro . Any information on how to get this API to work?

saddly, nope

**Comment by nonezonyx** [comment] 2023-03-04 06:57
same win10, api v5

**Comment by alejandroarmas** [comment] 2023-03-22 02:48
I'm having the same issue, has anyone gotten a work around so far? Any updates?

**Comment by VineWinner** [comment] 2023-04-19 02:18
> Hi all, I found out that the issue is caused because TikTok now expects to receive msToken in the cookie. To fix the issue, I added msToken in _get_cookies, as follows: ` if kwargs.get("force_verify_fp_on_cookie_header", False): return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "s_v_web_id": verifyFp, "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"), } else: return { "tt_webid": device_id, "tt_webid_v2": device_id, "csrf_session_id": kwargs.get("csrf_session_id"), "tt_csrf_token": "".join( random.choice(string.ascii_uppercase + string.ascii_lowercase) for i in range(16) ), "msToken": "<generated msToken>", "ttwid": kwargs.get("ttwid"),`
> 
> I used msToken that was generated by the browser in the request. If anyone has an idea how to automatically generate a valid msToken, please advise :)

i've made this process and the code still return the same message, did u get the api fixed?

**Comment by davidteather** [comment] 2023-08-08 21:54
Should be fixed in V6

**Closed by davidteather** 2023-08-08 21:54 UTC
Labels: bug
