### ISSUE TITLE
An error has ocurred, most of the time this is because the given username is not a valid username

### ISSUE THREAD

**Issue by selff** [davidteather/TikTok-Api#345] opened 2020-11-13 12:45 UTC
**Describe the bug**
i try use this endpoint (user/object/full?username=therock) in localhost and in rapidapi whit your app
https://tiktok2.p.rapidapi.com/user/object/full?username=therock
and receive error 

**The buggy code**

200

```
# Code Goes Here
```

**Expected behavior**

{2 items
"error":"An error has ocurred, most of the time this is because the given username is not a valid username."
"success":false
}

**Comment by hoylemd** [comment] 2020-11-13 15:42
There's currently a problem where TikTok is returning HTTP 200 with a body of 'illegal request' on a lot of (maybe all) endpoints. https://github.com/davidteather/TikTok-Api/issues/344

This is *probably* a duplicate of that.  Once we get that resolved I'll post here and you can try it again after an update.

**Comment by davidteather** [comment] 2020-11-13 17:27
Yeah more info on #344 and #342

**Closed** 2020-11-13 17:27 UTC
Labels: bug
